// <auto-generated />
using Mango.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250929065037_ProductTable")]
    partial class ProductTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Casual",
                            Description = "Lightweight and breathable sneakers perfect for daily wear.",
                            ImageUrl = "https://tse4.mm.bing.net/th/id/OIP.ttj3YyOLOlCTVIRcDRZaAgHaGR?w=193&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3",
                            Name = "UrbanWalk Sneakers",
                            Price = 2499.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Outdoor",
                            Description = "Durable boots with excellent grip for trekking and hiking.",
                            ImageUrl = "https://tse3.mm.bing.net/th/id/OIP.rexnCoYjJHefbqRr0YbrTQHaHa?w=211&h=211&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3",
                            Name = "TrailMaster Hiking Boots",
                            Price = 4999.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Formal",
                            Description = "Stylish heels for formal occasions and parties.",
                            ImageUrl = "https://tse2.mm.bing.net/th/id/OIP.LRyCYvWTL8VbrHpn_xeEgwHaHa?w=188&h=188&c=7&r=0&o=5&dpr=1.5&pid=1.7",
                            Name = "Elegance Stiletto Heels",
                            Price = 3299.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Casual",
                            Description = "Comfortable flip-flops ideal for beach and casual use.",
                            ImageUrl = "https://images.price.tools/images/oofoam-flip-flops-olive-7-l-1PWBfmps.jpg",
                            Name = "BeachEase Flip-Flops",
                            Price = 599.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
