// <auto-generated />
using Mango.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Casual",
                            Description = "Lightweight and breathable sneakers perfect for daily wear.",
                            ImageUrl = "https://example.com/images/urbanwalk.jpg",
                            Name = "UrbanWalk Sneakers",
                            Price = 2499.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Outdoor",
                            Description = "Durable boots with excellent grip for trekking and hiking.",
                            ImageUrl = "https://example.com/images/trailmaster.jpg",
                            Name = "TrailMaster Hiking Boots",
                            Price = 4999.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Formal",
                            Description = "Stylish heels for formal occasions and parties.",
                            ImageUrl = "https://example.com/images/elegance.jpg",
                            Name = "Elegance Stiletto Heels",
                            Price = 3299.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Casual",
                            Description = "Comfortable flip-flops ideal for beach and casual use.",
                            ImageUrl = "https://example.com/images/beachease.jpg",
                            Name = "BeachEase Flip-Flops",
                            Price = 599.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
